// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtPmv94KdFpd67O9tdM3uo_g_eH3nxhuQ',
    appId: '1:103702944485:web:4e8fffb91196223e03520c',
    messagingSenderId: '103702944485',
    projectId: 'extrack-dce96',
    authDomain: 'extrack-dce96.firebaseapp.com',
    storageBucket: 'extrack-dce96.appspot.com',
    measurementId: 'G-8JQM5MEW24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANEytyfY3ewSovm1kYsmYIMoysR1AYUq8',
    appId: '1:103702944485:android:b2e44243ab96960803520c',
    messagingSenderId: '103702944485',
    projectId: 'extrack-dce96',
    storageBucket: 'extrack-dce96.appspot.com',
  );
}
